apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: capsulechaosghostservice
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: capsulechaosghostservice
    spec:
      containers:
      - name: capsulechaosghostservice
        image: eu.gcr.io/capsulechaos/capsulechaosghostservice
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m              