name: Deploy PlayerActionValidationService

on:
  push:
    branches:
      - 'cheatdeploy'
      
jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
        
      - name: Test project via Unit Tests
        run: |-
          dotnet build ./PlayerActionValidationService/PlayerActionValidationService/PlayerActionValidationService.sln --configuration Release
          dotnet test ./PlayerActionValidationService/PlayerActionValidationService/PlayerActionValidationService.sln --configuration Release

      - name: Build Docker image
        run: |-
          docker build --tag "eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/capsulechaoscheatservice:latest" ./PlayerActionValidationService/PlayerActionValidationService/PlayerActionValidationService
      
      
      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      - name: Configure Docker to use Google Cloud Platform
        run: "gcloud auth configure-docker --quiet"
      - run: |-
            gcloud container clusters  get-credentials ${{ secrets.GCLOUD_CLUSTER }} --zone ${{ secrets.GCLOUD_ZONE }}
            
      - name: Push image to Google Cloud Container Registry
        run: "docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/capsulechaoscheatservice:latest"
     
     
      - name: Set up Kustomize
        working-directory: ./PlayerActionValidationService/PlayerActionValidationService/PlayerActionValidationService
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          
      - name: Deploy 
        working-directory: ./PlayerActionValidationService/PlayerActionValidationService/PlayerActionValidationService
        run: |-
          ./kustomize edit set image eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/capsulechaoscheatservice=eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/capsulechaoscheatservice:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/capsulechaoscheatservice
          kubectl get services -o wide