name: Unity Game Test and Build

on:
  push:
    branches:
      - 'unitygamedeploy'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Test and build Capsule-Chaos
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.3.3f1
        testMode:
          - editmode
        targetPlatform:
          - StandaloneWindows64
    steps:
      # Checkout
      - name: Checkout repository
        working-directory: ./CapsuleChaos_UnityGame
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        working-directory: ./CapsuleChaos_UnityGame
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        working-directory: ./CapsuleChaos_UnityGame
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: ${{ matrix.unityVersion }}
          
      # Build
      - name: Build project
        working-directory: ./CapsuleChaos_UnityGame
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output 
      - uses: actions/upload-artifact@v1
        working-directory: ./CapsuleChaos_UnityGame
        with:
          name: Build
          path: build
